# Generated by Django 4.1.7 on 2023-04-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
