# Generated by Django 4.1.7 on 2023-04-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_sales_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.customer'),
        ),
    ]
