# Generated by Django 3.1.7 on 2023-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'pending'), ('1', 'checked out')], default=None, max_length=20, null=True),
        ),
    ]
