# Generated by Django 4.1.7 on 2023-04-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_alter_discountproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountservice',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
