# Generated by Django 3.1.7 on 2023-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('checked out', 'checked out')], default=None, max_length=20, null=True),
        ),
    ]
